# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: deploy



env:
  CI: false
  HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: "monkey"

jobs:
  deployment:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: change access
      run: chmod +x ./mvnw
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.16.0'
    - name: Build with Maven
      run: mvn -e heroku:deploy